In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [55]:
df = pd.read_csv('transfusion.csv')
df.head()

Recency  Frequency   Monetary  Time  donated
0        2          50     12500    98        1
1        0          13      3250    28        1
2        1          16      4000    35        1
3        2          20      5000    45        1
4        1          24      6000    77        0

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Recency     748 non-null    int64
 1   Frequency   748 non-null    int64
 2   Monetary    748 non-null    int64
 3   Time        748 non-null    int64
 4   donated     748 non-null    int64
dtypes: int64(5)
memory usage: 29.3 KB


In [57]:
df.shape

(748, 5)

In [58]:
#checking for the null values
df.isnull().sum()

Recency       0
Frequency     0
Monetary      0
Time          0
donated       0
dtype: int64

In [59]:
#seperating the target and the feature variable
x = df.drop('donated',axis = 1)
y = df['donated']

In [60]:
#splitting the dataset into training and testing set - split 1
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.2, random_state = 0)



In [61]:
#creating a knn model for set 1 
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=3)

In [62]:
#estimating the classes for for first fit using knn
ypredknn1 = knn.predict(xtest)
ypredknn1



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [63]:
ytest

258    0
521    1
14     1
31     1
505    1
      ..
609    0
187    0
718    0
293    0
416    0
Name: donated, Length: 150, dtype: int64

In [64]:
#performance scores for set 1 knn
from sklearn.metrics import accuracy_score,recall_score,precision_score
acknn1 = accuracy_score(ytest,ypredknn1)
pcknn1 = precision_score(ytest,ypredknn1)
rcknn1 = recall_score(ytest,ypredknn1)
mcknn1 = 1 - acknn1


In [65]:
# decision tree classifier for split 1 
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier()
tree.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [66]:
ypreddct1 = tree.predict(xtest)
ypreddct1

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0], dtype=int64)

In [67]:
ytest1

258    0
521    1
14     1
31     1
505    1
      ..
609    0
187    0
718    0
293    0
416    0
Name: donated, Length: 150, dtype: int64

In [68]:
#performance scores for set 1 dct
acdct1 = accuracy_score(ytest,ypreddct1)
pcdct1 = precision_score(ytest,ypreddct1)
rcdct1 = recall_score(ytest,ypreddct1)
mcdct1 = 1 - acknn1


In [69]:
#split-2 
xtrain2,xtest2,ytrain2,ytest2 = train_test_split(x,y,test_size = 0.4, random_state = 0)

In [70]:
#creating a knn model for set 2 
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(xtrain2,ytrain2)

KNeighborsClassifier(n_neighbors=3)

In [71]:
ypredknn2 = knn.predict(xtest2)
ypredknn2

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1], d

In [72]:
ytest2


258    0
521    1
14     1
31     1
505    1
      ..
595    0
356    0
107    0
133    0
532    0
Name: donated, Length: 300, dtype: int64

In [73]:
#performance scores for set 2 knn
acknn2 = accuracy_score(ytest2,ypredknn2)
pcknn2 = precision_score(ytest2,ypredknn2)
rcknn2 = recall_score(ytest2,ypredknn2)
mcknn2 = 1 - acknn2

In [74]:
# decision tree classifier for split 2 
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier()
tree.fit(xtrain2,ytrain2)

DecisionTreeClassifier()

In [75]:
ypreddct2 = tree.predict(xtest2)
ypreddct2

array([1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0], d

In [76]:
ytest2

258    0
521    1
14     1
31     1
505    1
      ..
595    0
356    0
107    0
133    0
532    0
Name: donated, Length: 300, dtype: int64

In [78]:
#performance scores for dct set 2
acdct2 = accuracy_score(ytest2,ypreddct2)
pcdct2 = precision_score(ytest2,ypreddct2)
rcdct2 = recall_score(ytest2,ypreddct2)
mcdct2 = 1 - acknn2

In [80]:
#split 3 
xtrain3,xtest3,ytrain3,ytest3 = train_test_split(x,y,test_size = 0.7, random_state = 0)

In [81]:
#creating a knn model for set 3 
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(xtrain3,ytrain3)

KNeighborsClassifier(n_neighbors=3)

In [89]:
ypredknn3 = knn.predict(xtest3)
ypredknn3

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,

In [90]:
ytest3

258    0
521    1
14     1
31     1
505    1
      ..
114    0
508    1
602    0
176    1
168    0
Name: donated, Length: 524, dtype: int64

In [85]:
#performance scores for set 3 knn
acknn3 = accuracy_score(ytest3,ypredknn3)
pcknn3 = precision_score(ytest3,ypredknn3)
rcknn3 = recall_score(ytest3,ypredknn3)
mcknn3 = 1 - acknn3

In [86]:
# decision tree classifier for split 3 
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier()
tree.fit(xtrain3,ytrain3)

DecisionTreeClassifier()

In [87]:
ypreddct3 = tree.predict(xtest3)
ypreddct3

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,

In [88]:
ytest3

258    0
521    1
14     1
31     1
505    1
      ..
114    0
508    1
602    0
176    1
168    0
Name: donated, Length: 524, dtype: int64

In [91]:
#performance scores for dct set 3
acdct3 = accuracy_score(ytest3,ypreddct3)
pcdct3 = precision_score(ytest3,ypreddct3)
rcdct3 = recall_score(ytest3,ypreddct3)
mcdct3 = 1 - acknn3

In [99]:
overallknnac=(acknn1+acknn2+acknn3)/3
overalldctac =(acdct1+acdct2+acdct3)/3
overallknnpc=(pcknn1+pcknn2+pcknn3)/3
overalldctpc =(pcdct1+pcdct2+pcdct3)/3
overallknnrc=(rcknn1+rcknn2+rcknn3)/3
overalldctrc =(rcdct1+rcdct2+rcdct3)/3
overallknnmc=(mcknn1+mcknn2+mcknn3)/3
overalldctmc =(mcdct1+mcdct2+mcdct3)/3

results = {'algorithm':['knn','knn','knn','dct','dct','dct','overall_knn','overall_dct'],
           'accuracy_score':[acknn1,acknn2,acknn3,acdct1,acdct2,acdct3,overallknnac,overalldctac],
           'recall_score': [rcknn1,rcknn2,rcknn3,rcdct1,rcdct2,rcdct3,overallknnrc,overalldctrc],
           'precision_score':[pcknn1,pcknn2,pcknn3,pcdct1,pcdct2,pcdct3,overallknnpc,overalldctpc],
          'misclassifiction_rate':[mcknn1,mcknn2,mcknn3,mcdct1,mcdct2,mcdct3,overallknnmc,overalldctmc],
          'splits':[0.2,0.4,0.7,0.2,0.4,0.7,'null','null']}

In [106]:
results = pd.DataFrame(results)
results

algorithm  accuracy_score  recall_score  precision_score  \
0          knn        0.753333      0.341463         0.583333   
1          knn        0.740000      0.310811         0.460000   
2          knn        0.729008      0.198413         0.378788   
3          dct        0.693333      0.341463         0.424242   
4          dct        0.723333      0.364865         0.428571   
5          dct        0.685115      0.261905         0.314286   
6  overall_knn        0.740780      0.283562         0.474040   
7  overall_dct        0.700594      0.322744         0.389033   

   misclassifiction_rate splits  
0               0.246667    0.2  
1               0.260000    0.4  
2               0.270992    0.7  
3               0.246667    0.2  
4               0.260000    0.4  
5               0.270992    0.7  
6               0.259220   null  
7               0.259220   null

In [107]:
results.to_csv('results.csv',index = False)