In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [60]:
df = pd.read_csv('titanic.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [61]:
#metadata of the dataset 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [62]:
#preproccessing
mean_age = round(df['Age'].mean(),2)
df['Age'].fillna(mean_age,inplace = True)
df.isnull().sum()
df.dropna(inplace = True)
df.isnull().sum()
df.drop(['PassengerId','Ticket','Fare','Name','Cabin'],axis = 1,inplace = True)
filter1 = df['Age']<70
filter2 = df['Age']>1
df = df[filter1 & filter2]

In [63]:
#coverison of categorical variables to continuos
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])
df['Embarked'] = le.fit_transform(df['Embarked'])


In [64]:
#seperating the features and the target variable
x = df.drop(['Survived'],axis = 1)
y = df['Survived']

In [65]:
#splitting the test and train data 
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size = 0.8,random_state = 0)


In [66]:
#performing knn classification for k = 3 , euclidian
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors = 3)
model.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=3)

In [67]:
y_pred = model.predict(xtest)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [68]:
y_pred

array([1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1], dtype=int64)

In [69]:
ytest

505    0
62     0
796    1
339    0
690    1
303    1
539    1
839    1
438    0
102    0
27     0
21     1
724    1
730    1
879    1
748    0
332    0
310    1
585    1
740    1
248    1
453    1
185    0
556    1
621    1
618    1
711    0
92     0
591    1
498    0
205    0
782    0
572    1
124    0
577    1
815    0
11     1
806    0
340    1
434    0
Name: Survived, dtype: int64

In [70]:
#performace analysis for k = 3 , euclidian
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score,precision_score,f1_score
print(confusion_matrix(ytest,y_pred))
print(accuracy_score(ytest,y_pred))
ack3e = accuracy_score(ytest,y_pred)

[[ 9  9]
 [ 4 18]]
0.675


In [71]:
#performing knn for k =3,manhattan
model = KNeighborsClassifier(n_neighbors = 3,metric = 'manhattan')
model.fit(xtrain,ytrain)

KNeighborsClassifier(metric='manhattan', n_neighbors=3)

In [72]:
y_pred1 = model.predict(xtest)
y_pred1


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1], dtype=int64)

In [73]:
ytest

505    0
62     0
796    1
339    0
690    1
303    1
539    1
839    1
438    0
102    0
27     0
21     1
724    1
730    1
879    1
748    0
332    0
310    1
585    1
740    1
248    1
453    1
185    0
556    1
621    1
618    1
711    0
92     0
591    1
498    0
205    0
782    0
572    1
124    0
577    1
815    0
11     1
806    0
340    1
434    0
Name: Survived, dtype: int64

In [74]:
#performance analysis for k = 3, manhattan
print(confusion_matrix(ytest,y_pred1))
print(accuracy_score(ytest,y_pred1))
ack3m = accuracy_score(ytest,y_pred1)

[[ 9  9]
 [ 6 16]]
0.625


In [75]:
#performing knn for k = 3, jaccard
model = KNeighborsClassifier(n_neighbors = 3,metric = 'jaccard')
model.fit(xtrain,ytrain)

KNeighborsClassifier(metric='jaccard', n_neighbors=3)

In [76]:
y_pred2 = model.predict(xtest)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [77]:
y_pred2

array([1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0], dtype=int64)

In [78]:
ytest

505    0
62     0
796    1
339    0
690    1
303    1
539    1
839    1
438    0
102    0
27     0
21     1
724    1
730    1
879    1
748    0
332    0
310    1
585    1
740    1
248    1
453    1
185    0
556    1
621    1
618    1
711    0
92     0
591    1
498    0
205    0
782    0
572    1
124    0
577    1
815    0
11     1
806    0
340    1
434    0
Name: Survived, dtype: int64

In [79]:
#performance analysis of k = 3, jaccard
print(confusion_matrix(ytest,y_pred2))
print(accuracy_score(ytest,y_pred2))
ack3j = accuracy_score(ytest,y_pred2)

[[10  8]
 [ 6 16]]
0.65


In [80]:
#performing knn for k = 3, cosine
model = KNeighborsClassifier(n_neighbors = 3, metric = 'cosine')
model.fit(xtrain,ytrain)

KNeighborsClassifier(metric='cosine', n_neighbors=3)

In [81]:
y_pred4 = model.predict(xtest)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [82]:
y_pred4

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1], dtype=int64)

In [83]:
ytest

505    0
62     0
796    1
339    0
690    1
303    1
539    1
839    1
438    0
102    0
27     0
21     1
724    1
730    1
879    1
748    0
332    0
310    1
585    1
740    1
248    1
453    1
185    0
556    1
621    1
618    1
711    0
92     0
591    1
498    0
205    0
782    0
572    1
124    0
577    1
815    0
11     1
806    0
340    1
434    0
Name: Survived, dtype: int64

In [84]:
print(confusion_matrix(ytest,y_pred4))
print(accuracy_score(ytest,y_pred4))
ack3c = accuracy_score(ytest,y_pred4)

[[ 8 10]
 [ 5 17]]
0.625


In [85]:
#knn for k = 2,Euclidian
model2= KNeighborsClassifier(n_neighbors =2)
model2.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=2)

In [86]:
ypred2= model.predict(xtest)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [87]:
ypred2


array([1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1], dtype=int64)

In [88]:
ytest

505    0
62     0
796    1
339    0
690    1
303    1
539    1
839    1
438    0
102    0
27     0
21     1
724    1
730    1
879    1
748    0
332    0
310    1
585    1
740    1
248    1
453    1
185    0
556    1
621    1
618    1
711    0
92     0
591    1
498    0
205    0
782    0
572    1
124    0
577    1
815    0
11     1
806    0
340    1
434    0
Name: Survived, dtype: int64

In [89]:
#performance analysis for k = 2,Euclidean
print(confusion_matrix(ytest,ypred2))
print(accuracy_score(ytest,ypred2))
ack2e = accuracy_score(ytest,ypred2)

[[ 8 10]
 [ 5 17]]
0.625


In [90]:
#performing knn for k =2,manhattan
model2 = KNeighborsClassifier(n_neighbors = 2, metric = 'manhattan')
model2.fit(xtrain,ytrain)

KNeighborsClassifier(metric='manhattan', n_neighbors=2)

In [91]:
ypred2m = model2.predict(xtest)
ypred2m

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

In [92]:
ytest

505    0
62     0
796    1
339    0
690    1
303    1
539    1
839    1
438    0
102    0
27     0
21     1
724    1
730    1
879    1
748    0
332    0
310    1
585    1
740    1
248    1
453    1
185    0
556    1
621    1
618    1
711    0
92     0
591    1
498    0
205    0
782    0
572    1
124    0
577    1
815    0
11     1
806    0
340    1
434    0
Name: Survived, dtype: int64

In [93]:
#performance analysis for k = 2 , manhattan
print(confusion_matrix(ytest,ypred2m))
print(accuracy_score(ytest,ypred2m))
ack2m = accuracy_score(ytest,ypred2m)

[[12  6]
 [10 12]]
0.6


In [94]:
#performing knn for k = 2, jaccard
model2 = KNeighborsClassifier(n_neighbors = 2, metric = 'jaccard')
model2.fit(xtrain,ytrain)

KNeighborsClassifier(metric='jaccard', n_neighbors=2)

In [95]:
ypred2j = model2.predict(xtest)
ypred2j

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0], dtype=int64)

In [96]:
ytest


505    0
62     0
796    1
339    0
690    1
303    1
539    1
839    1
438    0
102    0
27     0
21     1
724    1
730    1
879    1
748    0
332    0
310    1
585    1
740    1
248    1
453    1
185    0
556    1
621    1
618    1
711    0
92     0
591    1
498    0
205    0
782    0
572    1
124    0
577    1
815    0
11     1
806    0
340    1
434    0
Name: Survived, dtype: int64

In [97]:
#performance analysis for k = 2 , jaccard
print(confusion_matrix(ytest,ypred2j))
print(accuracy_score(ytest,ypred2j))
ack2j = accuracy_score(ytest,ypred2j)

[[10  8]
 [ 7 15]]
0.625


In [98]:
#performing knn for k = 2 , cosine 
model2 = KNeighborsClassifier(n_neighbors = 2,metric = 'cosine')
model2.fit(xtrain,ytrain)

KNeighborsClassifier(metric='cosine', n_neighbors=2)

In [99]:
ypred2c = model2.predict(xtest)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [100]:
ypred2c


array([1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1], dtype=int64)

In [101]:
ytest

505    0
62     0
796    1
339    0
690    1
303    1
539    1
839    1
438    0
102    0
27     0
21     1
724    1
730    1
879    1
748    0
332    0
310    1
585    1
740    1
248    1
453    1
185    0
556    1
621    1
618    1
711    0
92     0
591    1
498    0
205    0
782    0
572    1
124    0
577    1
815    0
11     1
806    0
340    1
434    0
Name: Survived, dtype: int64

In [102]:
#performance analysis of k =3, cosine
print(confusion_matrix(ytest,ypred2c))
print(accuracy_score(ytest,ypred2c))
ack2c = accuracy_score(ytest,ypred2c)

[[10  8]
 [ 9 13]]
0.575


In [103]:
#knn for k = 1,euclidian 
model3 = KNeighborsClassifier(n_neighbors = 1)   
model3.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=1)

In [104]:
ypred3 = model3.predict(xtest)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [105]:
ypred3

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype=int64)

In [106]:
ytest


505    0
62     0
796    1
339    0
690    1
303    1
539    1
839    1
438    0
102    0
27     0
21     1
724    1
730    1
879    1
748    0
332    0
310    1
585    1
740    1
248    1
453    1
185    0
556    1
621    1
618    1
711    0
92     0
591    1
498    0
205    0
782    0
572    1
124    0
577    1
815    0
11     1
806    0
340    1
434    0
Name: Survived, dtype: int64

In [107]:
#performance analysis for k = 1
print(confusion_matrix(ytest,ypred3))
print(accuracy_score(ytest,ypred3))
ack1e = accuracy_score(ytest,ypred3)

[[10  8]
 [ 5 17]]
0.675


In [108]:
#knn for k =1, manhattan 
model3 = KNeighborsClassifier(n_neighbors = 1,metric = 'manhattan')   
model3.fit(xtrain,ytrain)

KNeighborsClassifier(metric='manhattan', n_neighbors=1)

In [109]:
ypred3m = model3.predict(xtest)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [110]:
ypred3m

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype=int64)

In [111]:
ytest

505    0
62     0
796    1
339    0
690    1
303    1
539    1
839    1
438    0
102    0
27     0
21     1
724    1
730    1
879    1
748    0
332    0
310    1
585    1
740    1
248    1
453    1
185    0
556    1
621    1
618    1
711    0
92     0
591    1
498    0
205    0
782    0
572    1
124    0
577    1
815    0
11     1
806    0
340    1
434    0
Name: Survived, dtype: int64

In [112]:
#performance analysis of k =1 ,  manhattan
print(confusion_matrix(ytest,ypred3m))
print(accuracy_score(ytest,ypred3m))
ack1m = accuracy_score(ytest,ypred3m)

[[10  8]
 [ 5 17]]
0.675


In [113]:
#knn for k =1 , jaccard
model3 = KNeighborsClassifier(n_neighbors = 1,metric = 'jaccard')   
model3.fit(xtrain,ytrain)

KNeighborsClassifier(metric='jaccard', n_neighbors=1)

In [114]:
ypred3j = model3.predict(xtest)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [115]:
ypred3j

array([1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0], dtype=int64)

In [116]:
ytest

505    0
62     0
796    1
339    0
690    1
303    1
539    1
839    1
438    0
102    0
27     0
21     1
724    1
730    1
879    1
748    0
332    0
310    1
585    1
740    1
248    1
453    1
185    0
556    1
621    1
618    1
711    0
92     0
591    1
498    0
205    0
782    0
572    1
124    0
577    1
815    0
11     1
806    0
340    1
434    0
Name: Survived, dtype: int64

In [117]:
#performance analysis for k = 1, jaccard
print(confusion_matrix(ytest,ypred3j))
print(accuracy_score(ytest,ypred3j))
ack1j = accuracy_score(ytest,ypred3j)

[[10  8]
 [ 7 15]]
0.625


In [118]:
#knn for k =1 , cosine
model3 = KNeighborsClassifier(n_neighbors = 1,metric = 'cosine')   
model3.fit(xtrain,ytrain)

KNeighborsClassifier(metric='cosine', n_neighbors=1)

In [119]:
ypred3c = model3.predict(xtest)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [120]:
ypred3c

array([1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype=int64)

In [121]:
np.array(ytest)

array([0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int64)

In [122]:
#performance analysis of k = 1, cosine
print(confusion_matrix(ytest,ypred3c))
print(accuracy_score(ytest,ypred3c))
ack1c = accuracy_score(ytest,ypred3c)

[[10  8]
 [ 6 16]]
0.65


In [123]:
#putting together the final output for all k and metrics 
final = { 'k' : [3,3,3,3,2,2,2,2,1,1,1,1],
'metrics' : ['euclidean','manhattan','jaccard','cosine','euclidean','manhattan','jaccard','cosine','euclidean','manhattan','jaccard','cosine']
,'accuracy_scores':[ack3e,ack3m,ack3j,ack3c,ack2e,ack2m,ack2j,ack2c,ack1e,ack1m,ack1j,ack1c]}

pd.DataFrame(final)

k    metrics  accuracy_scores
0   3  euclidean            0.675
1   3  manhattan            0.625
2   3    jaccard            0.650
3   3     cosine            0.625
4   2  euclidean            0.625
5   2  manhattan            0.600
6   2    jaccard            0.625
7   2     cosine            0.575
8   1  euclidean            0.675
9   1  manhattan            0.675
10  1    jaccard            0.625
11  1     cosine            0.650