In [131]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [132]:
df = pd.read_csv('wine.csv')
df.head()

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0     1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1     1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2     1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3     1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4     1    13.24        2.59  2.87  21.0  118     2.80        2.69   

   Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                  0.28     2.29       5.64  1.04  3.92     1065  
1                  0.26     1.28       4.38  1.05  3.40     1050  
2                  0.30     2.81       5.68  1.03  3.17     1185  
3                  0.24     2.18       7.80  0.86  3.45     1480  
4                  0.39     1.82       4.32  1.04  2.93      735

In [133]:
#metadata of the dataset 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Wine                  178 non-null    int64  
 1   Alcohol               178 non-null    float64
 2   Malic.acid            178 non-null    float64
 3   Ash                   178 non-null    float64
 4   Acl                   178 non-null    float64
 5   Mg                    178 non-null    int64  
 6   Phenols               178 non-null    float64
 7   Flavanoids            178 non-null    float64
 8   Nonflavanoid.phenols  178 non-null    float64
 9   Proanth               178 non-null    float64
 10  Color.int             178 non-null    float64
 11  Hue                   178 non-null    float64
 12  OD                    178 non-null    float64
 13  Proline               178 non-null    int64  
dtypes: float64(11), int64(3)
memory usage: 19.6 KB


In [134]:
#seperating the features and the target variable
x = df.drop(['Wine'],axis = 1)
y = df['Wine']

In [135]:
#splitting the test and train data 
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size = 0.8,random_state = 0)


In [136]:
#performing knn classification for k = 3 , euclidian
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors = 3)
model.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=3)

In [137]:
y_pred = model.predict(xtest)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [138]:
y_pred

array([1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 1, 3, 3, 2, 1, 1, 2, 1, 2, 1,
       3, 2, 1, 2, 2, 2, 3, 3, 1, 1, 2, 1, 1, 1], dtype=int64)

In [139]:
ytest

54     1
151    3
63     2
55     1
123    2
121    2
7      1
160    3
106    2
90     2
141    3
146    3
5      1
98     2
168    3
80     2
33     1
18     1
61     2
51     1
66     2
37     1
4      1
104    2
60     2
111    2
126    2
86     2
112    2
164    3
26     1
56     1
129    2
45     1
8      1
44     1
Name: Wine, dtype: int64

In [140]:
#performace analysis for k = 3 , euclidian
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score,precision_score,f1_score
print(confusion_matrix(ytest,y_pred))
print(accuracy_score(ytest,y_pred))
ack3e = accuracy_score(ytest,y_pred)

[[13  0  1]
 [ 1 13  2]
 [ 1  3  2]]
0.7777777777777778


In [141]:
#performing knn for k =3,manhattan
model = KNeighborsClassifier(n_neighbors = 3,metric = 'manhattan')
model.fit(xtrain,ytrain)

KNeighborsClassifier(metric='manhattan', n_neighbors=3)

In [142]:
y_pred1 = model.predict(xtest)
y_pred1


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([1, 3, 2, 1, 2, 2, 1, 3, 2, 2, 1, 2, 1, 3, 3, 2, 1, 1, 2, 1, 2, 1,
       3, 2, 1, 2, 2, 2, 3, 3, 1, 1, 2, 1, 1, 2], dtype=int64)

In [143]:
ytest

54     1
151    3
63     2
55     1
123    2
121    2
7      1
160    3
106    2
90     2
141    3
146    3
5      1
98     2
168    3
80     2
33     1
18     1
61     2
51     1
66     2
37     1
4      1
104    2
60     2
111    2
126    2
86     2
112    2
164    3
26     1
56     1
129    2
45     1
8      1
44     1
Name: Wine, dtype: int64

In [144]:
#performance analysis for k = 3, manhattan
print(confusion_matrix(ytest,y_pred1))
print(accuracy_score(ytest,y_pred1))
ack3m = accuracy_score(ytest,y_pred1)

[[12  1  1]
 [ 1 13  2]
 [ 1  1  4]]
0.8055555555555556


In [145]:
#performing knn for k = 3, jaccard
model = KNeighborsClassifier(n_neighbors = 3,metric = 'jaccard')
model.fit(xtrain,ytrain)

KNeighborsClassifier(metric='jaccard', n_neighbors=3)

In [146]:
y_pred2 = model.predict(xtest)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [147]:
y_pred2

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [148]:
ytest

54     1
151    3
63     2
55     1
123    2
121    2
7      1
160    3
106    2
90     2
141    3
146    3
5      1
98     2
168    3
80     2
33     1
18     1
61     2
51     1
66     2
37     1
4      1
104    2
60     2
111    2
126    2
86     2
112    2
164    3
26     1
56     1
129    2
45     1
8      1
44     1
Name: Wine, dtype: int64

In [149]:
#performance analysis of k = 3, jaccard
print(confusion_matrix(ytest,y_pred2))
print(accuracy_score(ytest,y_pred2))
ack3j = accuracy_score(ytest,y_pred2)

[[ 0 14  0]
 [ 0 16  0]
 [ 0  6  0]]
0.4444444444444444


In [150]:
#performing knn for k = 3, cosine
model = KNeighborsClassifier(n_neighbors = 3, metric = 'cosine')
model.fit(xtrain,ytrain)

KNeighborsClassifier(metric='cosine', n_neighbors=3)

In [151]:
y_pred4 = model.predict(xtest)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [152]:
y_pred4

array([1, 2, 2, 1, 2, 3, 1, 3, 2, 3, 1, 3, 1, 1, 3, 2, 1, 1, 2, 1, 2, 1,
       3, 2, 2, 2, 2, 2, 3, 3, 1, 1, 3, 1, 1, 1], dtype=int64)

In [153]:
ytest

54     1
151    3
63     2
55     1
123    2
121    2
7      1
160    3
106    2
90     2
141    3
146    3
5      1
98     2
168    3
80     2
33     1
18     1
61     2
51     1
66     2
37     1
4      1
104    2
60     2
111    2
126    2
86     2
112    2
164    3
26     1
56     1
129    2
45     1
8      1
44     1
Name: Wine, dtype: int64

In [154]:
print(confusion_matrix(ytest,y_pred4))
print(accuracy_score(ytest,y_pred4))
ack3c = accuracy_score(ytest,y_pred4)

[[13  0  1]
 [ 1 11  4]
 [ 1  1  4]]
0.7777777777777778


In [155]:
#knn for k = 2,Euclidian
model2= KNeighborsClassifier(n_neighbors =2)
model2.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=2)

In [156]:
ypred2= model.predict(xtest)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [157]:
ypred2


array([1, 2, 2, 1, 2, 3, 1, 3, 2, 3, 1, 3, 1, 1, 3, 2, 1, 1, 2, 1, 2, 1,
       3, 2, 2, 2, 2, 2, 3, 3, 1, 1, 3, 1, 1, 1], dtype=int64)

In [158]:
ytest

54     1
151    3
63     2
55     1
123    2
121    2
7      1
160    3
106    2
90     2
141    3
146    3
5      1
98     2
168    3
80     2
33     1
18     1
61     2
51     1
66     2
37     1
4      1
104    2
60     2
111    2
126    2
86     2
112    2
164    3
26     1
56     1
129    2
45     1
8      1
44     1
Name: Wine, dtype: int64

In [159]:
#performance analysis for k = 2,Euclidean
print(confusion_matrix(ytest,ypred2))
print(accuracy_score(ytest,ypred2))
ack2e = accuracy_score(ytest,ypred2)

[[13  0  1]
 [ 1 11  4]
 [ 1  1  4]]
0.7777777777777778


In [160]:
#performing knn for k =2,manhattan
model2 = KNeighborsClassifier(n_neighbors = 2, metric = 'manhattan')
model2.fit(xtrain,ytrain)

KNeighborsClassifier(metric='manhattan', n_neighbors=2)

In [161]:
ypred2m = model2.predict(xtest)
ypred2m

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 1, 3, 2, 2, 1, 1, 2, 1, 2, 1,
       2, 2, 1, 2, 2, 2, 3, 3, 1, 1, 2, 1, 1, 1], dtype=int64)

In [162]:
ytest

54     1
151    3
63     2
55     1
123    2
121    2
7      1
160    3
106    2
90     2
141    3
146    3
5      1
98     2
168    3
80     2
33     1
18     1
61     2
51     1
66     2
37     1
4      1
104    2
60     2
111    2
126    2
86     2
112    2
164    3
26     1
56     1
129    2
45     1
8      1
44     1
Name: Wine, dtype: int64

In [163]:
#performance analysis for k = 2 , manhattan
print(confusion_matrix(ytest,ypred2m))
print(accuracy_score(ytest,ypred2m))
ack2m = accuracy_score(ytest,ypred2m)

[[13  1  0]
 [ 1 13  2]
 [ 1  4  1]]
0.75


In [164]:
#performing knn for k = 2, jaccard
model2 = KNeighborsClassifier(n_neighbors = 2, metric = 'jaccard')
model2.fit(xtrain,ytrain)

KNeighborsClassifier(metric='jaccard', n_neighbors=2)

In [165]:
ypred2j = model2.predict(xtest)
ypred2j

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [166]:
ytest


54     1
151    3
63     2
55     1
123    2
121    2
7      1
160    3
106    2
90     2
141    3
146    3
5      1
98     2
168    3
80     2
33     1
18     1
61     2
51     1
66     2
37     1
4      1
104    2
60     2
111    2
126    2
86     2
112    2
164    3
26     1
56     1
129    2
45     1
8      1
44     1
Name: Wine, dtype: int64

In [167]:
#performance analysis for k = 2 , jaccard
print(confusion_matrix(ytest,ypred2j))
print(accuracy_score(ytest,ypred2j))
ack2j = accuracy_score(ytest,ypred2j)

[[ 0 14  0]
 [ 0 16  0]
 [ 0  6  0]]
0.4444444444444444


In [168]:
#performing knn for k = 2 , cosine 
model2 = KNeighborsClassifier(n_neighbors = 2,metric = 'cosine')
model2.fit(xtrain,ytrain)

KNeighborsClassifier(metric='cosine', n_neighbors=2)

In [169]:
ypred2c = model2.predict(xtest)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [170]:
ypred2c


array([1, 2, 2, 1, 2, 2, 1, 3, 2, 2, 1, 3, 1, 1, 3, 2, 1, 1, 2, 1, 2, 1,
       3, 2, 1, 2, 2, 2, 3, 3, 1, 1, 3, 1, 1, 1], dtype=int64)

In [171]:
ytest

54     1
151    3
63     2
55     1
123    2
121    2
7      1
160    3
106    2
90     2
141    3
146    3
5      1
98     2
168    3
80     2
33     1
18     1
61     2
51     1
66     2
37     1
4      1
104    2
60     2
111    2
126    2
86     2
112    2
164    3
26     1
56     1
129    2
45     1
8      1
44     1
Name: Wine, dtype: int64

In [172]:
#performance analysis of k =3, cosine
print(confusion_matrix(ytest,ypred2c))
print(accuracy_score(ytest,ypred2c))
ack2c = accuracy_score(ytest,ypred2c)

[[13  0  1]
 [ 2 12  2]
 [ 1  1  4]]
0.8055555555555556


In [173]:
#knn for k = 1,euclidian 
model3 = KNeighborsClassifier(n_neighbors = 1)   
model3.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=1)

In [174]:
ypred3 = model3.predict(xtest)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [175]:
ypred3

array([1, 2, 2, 1, 2, 2, 1, 3, 2, 2, 1, 2, 1, 3, 3, 2, 1, 1, 2, 1, 2, 1,
       2, 2, 1, 2, 2, 2, 3, 3, 1, 1, 3, 1, 1, 1], dtype=int64)

In [176]:
ytest


54     1
151    3
63     2
55     1
123    2
121    2
7      1
160    3
106    2
90     2
141    3
146    3
5      1
98     2
168    3
80     2
33     1
18     1
61     2
51     1
66     2
37     1
4      1
104    2
60     2
111    2
126    2
86     2
112    2
164    3
26     1
56     1
129    2
45     1
8      1
44     1
Name: Wine, dtype: int64

In [177]:
#performance analysis for k = 1
print(confusion_matrix(ytest,ypred3))
print(accuracy_score(ytest,ypred3))
ack1e = accuracy_score(ytest,ypred3)

[[13  1  0]
 [ 1 12  3]
 [ 1  2  3]]
0.7777777777777778


In [178]:
#knn for k =1, manhattan 
model3 = KNeighborsClassifier(n_neighbors = 1,metric = 'manhattan')   
model3.fit(xtrain,ytrain)

KNeighborsClassifier(metric='manhattan', n_neighbors=1)

In [179]:
ypred3m = model3.predict(xtest)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [180]:
ypred3m

array([1, 3, 2, 1, 2, 2, 1, 3, 2, 2, 1, 2, 1, 3, 3, 2, 1, 1, 2, 1, 2, 1,
       2, 2, 2, 2, 2, 2, 3, 3, 1, 1, 3, 1, 1, 1], dtype=int64)

In [181]:
ytest

54     1
151    3
63     2
55     1
123    2
121    2
7      1
160    3
106    2
90     2
141    3
146    3
5      1
98     2
168    3
80     2
33     1
18     1
61     2
51     1
66     2
37     1
4      1
104    2
60     2
111    2
126    2
86     2
112    2
164    3
26     1
56     1
129    2
45     1
8      1
44     1
Name: Wine, dtype: int64

In [182]:
#performance analysis of k =1 ,  manhattan
print(confusion_matrix(ytest,ypred3m))
print(accuracy_score(ytest,ypred3m))
ack1m = accuracy_score(ytest,ypred3m)

[[13  1  0]
 [ 0 13  3]
 [ 1  1  4]]
0.8333333333333334


In [183]:
#knn for k =1 , jaccard
model3 = KNeighborsClassifier(n_neighbors = 1,metric = 'jaccard')   
model3.fit(xtrain,ytrain)

KNeighborsClassifier(metric='jaccard', n_neighbors=1)

In [184]:
ypred3j = model3.predict(xtest)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [185]:
ypred3j

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [186]:
ytest

54     1
151    3
63     2
55     1
123    2
121    2
7      1
160    3
106    2
90     2
141    3
146    3
5      1
98     2
168    3
80     2
33     1
18     1
61     2
51     1
66     2
37     1
4      1
104    2
60     2
111    2
126    2
86     2
112    2
164    3
26     1
56     1
129    2
45     1
8      1
44     1
Name: Wine, dtype: int64

In [187]:
#performance analysis for k = 1, jaccard
print(confusion_matrix(ytest,ypred3j))
print(accuracy_score(ytest,ypred3j))
ack1j = accuracy_score(ytest,ypred3j)

[[ 0 14  0]
 [ 0 16  0]
 [ 0  6  0]]
0.4444444444444444


In [188]:
#knn for k =1 , cosine
model3 = KNeighborsClassifier(n_neighbors = 1,metric = 'cosine')   
model3.fit(xtrain,ytrain)

KNeighborsClassifier(metric='cosine', n_neighbors=1)

In [189]:
ypred3c = model3.predict(xtest)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [190]:
ypred3c

array([1, 3, 2, 1, 2, 2, 1, 3, 2, 2, 1, 3, 1, 2, 3, 2, 1, 1, 2, 1, 2, 1,
       3, 2, 2, 2, 2, 3, 3, 3, 1, 1, 3, 1, 1, 1], dtype=int64)

In [191]:
np.array(ytest)

array([1, 3, 2, 1, 2, 2, 1, 3, 2, 2, 3, 3, 1, 2, 3, 2, 1, 1, 2, 1, 2, 1,
       1, 2, 2, 2, 2, 2, 2, 3, 1, 1, 2, 1, 1, 1], dtype=int64)

In [192]:
#performance analysis of k = 1, cosine
print(confusion_matrix(ytest,ypred3c))
print(accuracy_score(ytest,ypred3c))
ack1c = accuracy_score(ytest,ypred3c)

[[13  0  1]
 [ 0 13  3]
 [ 1  0  5]]
0.8611111111111112


In [198]:
#putting together the final output for all k and metrics 
final = { 'k' : [3,3,3,3,2,2,2,2,1,1,1,1],
'metrics' : ['euclidean','manhattan','jaccard','cosine','euclidean','manhattan','jaccard','cosine','euclidean','manhattan','jaccard','cosine']
,'accuracy_scores':[ack3e,ack3m,ack3j,ack3c,ack2e,ack2m,ack2j,ack2c,ack1e,ack1m,ack1j,ack1c]}

pd.DataFrame(final)

k    metrics  accuracy_scores
0   3  euclidean         0.777778
1   3  manhattan         0.805556
2   3    jaccard         0.444444
3   3     cosine         0.777778
4   2  euclidean         0.777778
5   2  manhattan         0.750000
6   2    jaccard         0.444444
7   2     cosine         0.805556
8   1  euclidean         0.777778
9   1  manhattan         0.833333
10  1    jaccard         0.444444
11  1     cosine         0.861111