In [5]:
#matrix from user input
l =[]
n = int(input("Enter the number of rows :"))
m = int(input("Enter the number of columns :"))
print("Enter elements")
for i in range(n):
    a =[]
    for j in range(0,m):
        a.append(int(input()))
    l.append(a)
        
print("Matrix is :")
for i in range(n):
    for j in range(m):
        print(l[i][j], end = " ")
    print()


Enter the number of rows :3
Enter the number of columns :3
Enter elements
1
2
3
4
5
65
6
7
4
Matrix is :
1 2 3 
4 5 65 
6 7 4 


In [8]:
import numpy as np
#matrix multiplication
#matrix 1 entry
m1=[]
print("Enter matrix A :")
n = int(input("Enter the number of rows :"))
m = int(input("Enter the number of columns :"))
print("Enter elements")
for i in range(n):
    a =[]
    for j in range(0,m):
        a.append(int(input()))
    m1.append(a)
    
#matrix 2 entry
print("Enter matrix B :")
m2=[]
p = int(input("Enter the number of rows :"))
q = int(input("Enter the number of columns :"))
print("Enter elements")
for i in range(n):
    b =[]
    for j in range(0,m):
        a.append(int(input()))
    m2.append(a)

result = [[0 for j in range(q)] for i in range(n)]
        
   # Perform matrix multiplication
for i in range(n):
    for j in range(q):
        for k in range(p):
            result[i][j] += m1[i][k] * m2[k][j]

    # Print the result matrix
print("Resultant matrix:")
for row in result:
    print(row)

Enter matrix A :
Enter elements
Enter matrix B :
Enter elements
Resultant matrix:
[9, 12]
[21, 28]


In [7]:
#transpose of the matrix 
m1=[]
print("Enter matrix A :")
n = int(input("Enter the number of rows :"))
m = int(input("Enter the number of columns :"))
print("Enter elements")
for i in range(n):
    a =[]
    for j in range(0,m):
        a.append(int(input()))
    m1.append(a)


transpose = [[m1[j][i] for j in range(n)] for i in range(m)]

# Print the original matrix and the transposed matrix
print("Original matrix:")
for row in m1:
    print(row)
print("Transposed matrix:")
for row in transpose:
    print(row)

Enter matrix A :
Enter elements
Original matrix:
[1, 2]
[3, 4]
Transposed matrix:
[1, 3]
[2, 4]


In [2]:
import numpy as np

def cofactor(matrix, i, j):
    # Calculate the cofactor of the element at (i,j)
    sign = (-1) ** (i + j)
    minor = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
    return sign * np.linalg.det(minor)

def inverse(matrix):
    # Calculate the determinant of the input matrix
    det = np.linalg.det(matrix)
    if det == 0:
        raise ValueError("Input matrix is singular and has no inverse.")
    
    # Calculate the adjugate matrix
    n = matrix.shape[0]
    adjugate = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            adjugate[j, i] = cofactor(matrix, i, j)
    
    # Calculate the inverse matrix
    inverse = adjugate / det
    return inverse

# Get user input for the matrix
n = int(input("Enter the size of the square matrix: "))
matrix = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        matrix[i, j] = float(input(f"Enter element ({i+1}, {j+1}): "))

# Calculate and print the inverse matrix
try:
    inv_matrix = inverse(matrix)
    print("The inverse matrix is:")
    print(inv_matrix)
except ValueError as e:
    print(e)


Enter the size of the square matrix: 3
Enter element (1, 1): 1
Enter element (1, 2): 2
Enter element (1, 3): 3
Enter element (2, 1): 4
Enter element (2, 2): 5
Enter element (2, 3): 6
Enter element (3, 1): 7
Enter element (3, 2): 8
Enter element (3, 3): 9
The inverse matrix is:
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [11]:
#cramers rule

import numpy as np

def cramers_rule(coefficients, constants):
    n = len(coefficients)
    detA = np.linalg.det(coefficients)
    solutions = []
    for i in range(n):
        A_i = np.copy(coefficients)
        A_i[:, i] = constants
        detA_i = np.linalg.det(A_i)
        if detA != 0:
            x_i = detA_i / detA
            solutions.append(x_i)
        else:
            return None  # Cramer's rule does not apply if detA = 0
    return solutions

coefficients = np.array([[1, 1, 1], [2, -1, 1], [-1, 2, -1]])
constants = np.array([6, 3, 2])

solutions = cramers_rule(coefficients, constants)

if solutions is not None:
    print("Solution for x:", solutions[0])
    print("Solution for y:", solutions[1])
    print("Solution for z:", solutions[2])
else:
    print("Cramer's rule does not apply to this system of equations.")


Solution for x: 2.333333333333333
Solution for y: 2.666666666666668
Solution for z: 1.0
